load = true
name = "alarm"#app名称
module = 'alarm' #后台模块加上这行


[owner]
name = "xuyao"
organization = "smartspc"
bio = "实时告警"# 说明简介
dob = "2018-6-5" # 创建日期



[[route]]
name = ""
path = ""
component = ""
	# 需要登录
	[route.meta]
	requiresAuth = true



